apiVersion: v1
kind: Service
metadata:
  name: my-service-todo-django-app
spec:
  type: NodePort
  selector:
    app: todo-django-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007
